### ISSUE TITLE
Gateway timeouts using CURL method

### ISSUE THREAD

**Issue by kz6fittycent** [robvanbakel/gotiny-api#2]
Not sure if it's PEBKAC or if there's an issue but I'm getting gateway timeouts when using the referenced method in the README:

```
curl -X POST https://gotiny.cc/api -H "Content-Type: application/json" -d '{ "input" : "www.my-superlong-url-here.com" }'
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

Are you able to confirm?

**Comment by robvanbakel** [comment]
The server did indeed show an error, but should be up and running again now. Thanks a lot for the warning!
