### ISSUE TITLE
SSL Expired

### ISSUE THREAD

**Issue by kz6fittycent** [robvanbakel/gotiny-api#4]
Hey, just noticed this today:

![image](https://user-images.githubusercontent.com/14829816/169887574-e9219d53-1b50-4c4b-ac6c-30b3b2c877d2.png)

**Comment by robvanbakel** [comment]
That's odd, it shouldn't have expired yet. The issue is fixed for now; I'll further investigate what went wrong so it won't happen again in the future. Thanks for letting me know!
