### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by kz6fittycent** [robvanbakel/gotiny-api#9]
Hey, 

I just wanted to ping you about this: 

![image](https://user-images.githubusercontent.com/14829816/226392038-b4c916b2-cd23-42be-a46d-3ff9ac1bdc25.png)

P.S. Gotiny is awesome! Keep up the great work!!

**Comment by robvanbakel** [comment]
Thank you for letting me know, this one slipped through my fingers! The certificate is renewed and GoTiny is up again. Glad to hear you're enjoying the API!
